### ISSUE TITLE
[Readability] Please show time in 24h format in the explorer

### ISSUE THREAD

**Issue by antonionardella** [iot2tangle/Streams-explorer#3]
Hello,

if possible show the timestamp in 24h format in the explorer the 12h format can be confusing.

![image](https://user-images.githubusercontent.com/7383572/96183470-344cd300-0f37-11eb-91f5-5ddc3b7e4ac8.png)

Thank you!

**Comment by demichele** [comment]
We are working on some new features (channel id via GET on url and other details) and will include this suggestion soon. Thanks!

**Comment by eduardopelitti** [comment]
Done @antonionardella!
